apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-mah8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-mah8
    app.kubernetes.io/part-of: my-app
  name: dc-metro-map-mah8
  namespace: mkovarik-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map-mah8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map-mah8
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:0c83130cba3097bc8ed8950821f767829d5ba49629b6039cb59edd7f1035521b
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
